Fix trial ends at
laravel/cashier-paddle pull request #87
Opened 2020-10-16 14:17 UTC by yoeriboven

Fixes #85 

### Problem
Currently the `trialEndsAt` method checks if the user is on a generic trial. If it is then `trial_ends_at` on the User table will be returned. If it's not the trial of a subscription record will be returned.

This means that if a user used to be on a generic trial which is now expired, it will look for a (non-existent) subscription record instead of the `trial_ends_at` field and throw an exception.

### Solution
With this PR `trialEndsAt` will check if there is a subscription. If there is not a subscription it will return the date from the `trial_ends_at` field. If there is a subscription, it will return the subscription.

2020-10-16 18:41 UTC, GrahamCampbell requested changes

2020-10-16 18:41 UTC, GrahamCampbell commented on src/Concerns/ManagesSubscriptions.php
> +        if (is_null($this->subscription($name))) {
Should not double call this.

2020-10-19 08:00 UTC, driesvints approved these changes
Lgtm. Thanks @yoeriboven.

2020-10-19 08:16 UTC, driesvints commented
This actually also solves a problem with the `onGenericTrial` that checks if the trial date is in the future, which isn't needed. You just want the end date back, regardless of the trial having ended or not.

2020-10-19 09:36 UTC, GrahamCampbell approved these changes

2020-10-19 13:34 UTC, merged